apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: yoda-RN-for-yoda-rolebinding
  namespace: app-namespace
subjects:
- kind: User
  name: system:serviceaccount:app-namespace:yoda # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: RN-for-yoda # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io