---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  #- name: Check Vector process
  #  ansible.builtin.shell: 
  #    cmd: 'systemctl status vector.service'
  #  register: vector_service_status
  #  when: ansible_virtualization_type != "docker"
  - name: Check Vector version
    ansible.builtin.shell: 
      cmd: 'vector --version'
    register: vector_version_status  
  - name: Check Vector data_dir
    ansible.builtin.shell: 
      cmd: 'grep ^data_dir /etc/vector/vector.toml'
  - name: Check release codes from Vector checking 
    assert:
      that: 
  #      - vector_service_status.rc == 0
        - vector_version_status.rc == 0