all:
  hosts:
    cp1:
      ansible_host: 192.168.250.10
      ip: 192.168.250.10
      access_ip: 192.168.250.10
      ansible_user: dgolodnikov
    node1:
      ansible_host: 192.168.250.25
      ip: 192.168.250.25
      access_ip: 192.168.250.25
      ansible_user: dgolodnikov
    node2:
      ansible_host: 192.168.250.19
      ip: 192.168.250.19
      access_ip: 192.168.250.19
      ansible_user: dgolodnikov
    node3:
      ansible_host: 192.168.250.37
      ip: 192.168.250.37
      access_ip: 192.168.250.37
      ansible_user: dgolodnikov
    node4:
      ansible_host: 192.168.250.9
      ip: 192.168.250.9
      access_ip: 192.168.250.9
      ansible_user: dgolodnikov
  children:
    kube_control_plane:
      hosts:
        cp1:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
        node4:
    etcd:
      hosts:
        cp1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
