---
clickhouse_version: "22.3.3.44"
clickhouse_packages:
  - clickhouse-common-static
  - clickhouse-client
  - clickhouse-server
clickhouse_listen_host: "0.0.0.0"
vector_version: "0.22.0"
lighthouse_repo: "https://github.com/VKCOM/lighthouse.git"
lighthouse_dir: "/var/www/lighthouse"
  
