galaxy_info:
  role_name: vector
  author: DG
  description: Role for installation Vector
  company: Home

  license: MIT

  platforms:
    - name: Ubuntu
      versions:
        - focal
        - bionic
        - xenial

  min_ansible_version: 2.8
  galaxy_tags: 
    - vector

dependencies: []