apiVersion: v1
kind: Service
metadata:
  name: grafana-access
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: grafana
    #app.kubernetes.io/part-of: kube-prometheus
    #app.kubernetes.io/component: grafana  
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30123
      protocol: TCP
