apiVersion: v1
kind: Service
metadata: 
  name: vault
spec:
  selector:
    app: vault
  type: NodePort
  ports:
    - name: http
      port: 8200
      targetPort: 8200
      nodePort: 30010
      protocol: TCP