apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontweb
  name: front
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontweb
  template:
    metadata:
      labels:
        app: frontweb
    spec:
      containers:
      - image: "dgolodnikov/netofrontend:1.0.0"
        imagePullPolicy: IfNotPresent
        name: front
        env:
        - name: BASE_URL
          value: "http://backweb:30001"
        - name: SECRET_TLSCRT
          valueFrom:
            secretKeyRef:
              name: domain-cert
              key: tls.crt
        - name: SECRET_TLSKEY
          valueFrom:
            secretKeyRef:
              name: domain-cert
              key: tls.key