apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
  namespace: default
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: "dgolodnikov/netofrontend:1.0.0"
        imagePullPolicy: IfNotPresent
        name: front
      - image: "dgolodnikov/netobackend:1.0.0"
        imagePullPolicy: IfNotPresent
        name: back
---
apiVersion: apps/v1 
kind: StatefulSet
metadata:
  name: db
  namespace: default
  labels:
    app: db-web
spec:
  replicas: 1
  updateStrategy:
    type: "RollingUpdate"
  selector:
    matchLabels:
      app: db-web
  template:
    metadata:
      labels:
        app: db-web
    spec:
      containers:
        - name: postgres
          image: postgres:13-alpine
          imagePullPolicy: "IfNotPresent"
          env:
          - name: POSTGRES_PASSWORD
            value: postgres
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_DB
            value: news
          - name: PGDATA
            value: /data
          volumeMounts:
            - name: postgres-volume
              mountPath: /data
      volumes:
        - name: postgres-volume
          persistentVolumeClaim:
            claimName: pvc-postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgres 
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/pv