apiVersion: v1
kind: Service
metadata: 
  name: front
spec:
  selector:
    app: frontweb
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30002
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata: 
  name: back
spec:
  selector:
    app: backweb
  type: NodePort
  ports:
    - name: http
      port: 9000
      targetPort: 9000
      nodePort: 30001
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata: 
  name: dbweb
spec:
  selector:
    app: dbweb
  type: ClusterIP
  ports:
    - name: db
      port: 5432
      targetPort: 5432
      protocol: TCP   