galaxy_info:
  role_name: lighthouse
  author: DG
  description: Role for installation lighthouse
  company: Home

  license: MIT

  platforms:
    - name: Ubuntu
      versions:
        - focal
        - bionic
        - xenial

  min_ansible_version: 2.8
  galaxy_tags: 
    - lighthouse

dependencies: []