---
# tasks file for roles/vector
#- name: Get Vector distrib by get_url
#  ansible.builtin.get_url:
#    url: 'https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-gnu.tar.gz'
#    dest: '{{ ansible_facts["env"]["HOME"] }}/vector_{{ vector_version }}_tar.gz'
#- name: Mkdir for Vector by file
#  ansible.builtin.file:
#    path: '{{ ansible_facts["env"]["HOME"] }}/vector'
#    state: directory
#    mode: '0755'
#- name: UnZIP Vector
#  ansible.builtin.unarchive:
#    src: '{{ ansible_facts["env"]["HOME"] }}/vector_{{ vector_version }}_tar.gz'
#   dest: '{{ ansible_facts["env"]["HOME"] }}/vector'
#   remote_src: yes
#    extra_opts: [--strip-components=2]
#- name: Add EnvPATH to profile
#  ansible.builtin.lineinfile:
#    dest: '{{ ansible_facts["env"]["HOME"] }}/.profile'
#    regexp: ^export
#    line: 'export PATH="$HOME/vector/bin:$PATH"'
#- name: Commit EnvPATH
#  ansible.builtin.shell:
#    cmd: 'source $HOME/.profile'
#    executable: /bin/bash
#  register: path
#- name: CHECK EnvPATH and other VAR 
#  ansible.builtin.debug:
#    msg: 'PATH variables {{ path.stdout }}, HOME directory {{ ansible_facts["env"]["HOME"] }}, VM IP {{ vmip2 }}'
#- name: ADD group vector for Vector
#  become: true
#  ansible.builtin.group:
#    name: vector
#    state: present
#- name: ADD user vector for Vector
#  become: true
#  ansible.builtin.user:
#    name: vector
#    groups: vector
#    shell: /bin/bash
#- name: Change vector.service file for systemd
#  ansible.builtin.lineinfile:
#    dest: '{{ ansible_facts["env"]["HOME"] }}/vector/etc/systemd/vector.service'
#    regexp: ^ExecStart=
#    line: 'ExecStart={{ ansible_facts["env"]["HOME"] }}/vector/bin/vector --config {{ ansible_facts["env"]["HOME"] }}/vector/config/vector.toml'
#- name: Change vector.service file for systemd. Disable PreStart
#  ansible.builtin.lineinfile:
#    dest: '{{ ansible_facts["env"]["HOME"] }}/vector/etc/systemd/vector.service'
#    regexp: ^ExecStartPre=
#    line: '#'
- name: Add Vector REPO to SourceList
  ansible.builtin.shell:
    cmd: "curl -1sLf 'https://repositories.timber.io/public/vector/cfg/setup/bash.deb.sh' | bash"
    executable: /bin/bash
  changed_when: false
- name: Install VECTOR by APT
  become: true
  ansible.builtin.apt:
    update_cache: yes
    package: "vector"
- name: Vector config
  become: true
  ansible.builtin.template: 
    src: 'templates/vector.toml.j2'
    dest: '/etc/vector/vector.toml'
    mode: 0644
    owner: '{{ ansible_user_id }}'
    group: '{{ ansible_user_gid }}'
- name: ADD vector.service to system dir
  become: true
  ansible.builtin.template: 
    src: 'templates/vector.service.j2'
    dest: /etc/systemd/system/vector.service
    mode: 0644
    owner: '{{ ansible_user_id }}'
    group: '{{ ansible_user_gid }}'
- name: Starting vector by systemd
  become: true
  ansible.builtin.systemd:
    name: vector
    state: started
    enabled: yes
  when: ansible_virtualization_type != "docker"