apiVersion: v1
kind: Service
metadata: 
  name: application-access
spec:
  selector:
    app: nginx-webapp
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: {{ .Values.spec.ports.nodePort }} 
      protocol: TCP