apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: front-and-back
  namespace: default
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: "dgolodnikov/netofrontend:1.0.0"
        imagePullPolicy: IfNotPresent
        name: front
        env:
        - name: BASE_URL
          value: "http://backip:30001"
        volumeMounts:
        - mountPath: "/static-front"
          name: temp-volume
      - image: "dgolodnikov/netobackend:1.0.0"
        imagePullPolicy: IfNotPresent
        name: backend
        env:
        - name: DATABASE_URL
          value: "postgres://postgres:postgres@dbweb:5432/news"
        volumeMounts:
        - mountPath: "/static-back"
          name: temp-volume
      volumes:
      - name: temp-volume
        emptyDir: {}
---
apiVersion: apps/v1 
kind: StatefulSet
metadata:
  name: dbweb
  namespace: default
  labels:
    app: dbweb
spec:
  replicas: 1
  updateStrategy:
    type: "RollingUpdate"
  selector:
    matchLabels:
      app: dbweb
  template:
    metadata:
      labels:
        app: dbweb
    spec:
      containers:
        - name: postgres
          image: postgres:13-alpine
          imagePullPolicy: "IfNotPresent"
          env:
          - name: POSTGRES_PASSWORD
            value: postgres
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_DB
            value: news
          - name: PGDATA
            value: /data
          volumeMounts:
            - name: postgres-volume
              mountPath: /data
      volumes:
        - name: postgres-volume
          persistentVolumeClaim:
            claimName: pvc-postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgres 
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/pv
---

