apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: multitool
  name: multitool
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  multitool
  template:
    metadata:
      labels:
        app:  multitool
    spec:
      containers:
      - image: "praqma/network-multitool:alpine-extra"
        imagePullPolicy: IfNotPresent
        name: network-multitool
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: multitool
  namespace: default
spec:
  selector:
    app: multitool
#  type: NodePort
  ports:
    - name: http
      port: 80
#      targetPort: 80
#     nodePort: 31031